<//php_template

namespace <?= $this->invokerPackage . "\\" . $this->apiPackage ?>;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use SalesForce\MarketingCloud\Configuration;
use SalesForce\MarketingCloud\Authorization\AuthServiceSetup;
use SalesForce\MarketingCloud\Authorization\AuthService;

/**
 * Class <?= $this->clientClassName . PHP_EOL ?>
 *
 * NOTE: This class is auto generated
 *
 * @package <?= $this->invokerPackage . "\\" . $this->apiPackage . PHP_EOL ?>
 * @method self setAccountId(string $accountId)
 * @method self setClientId(string $clientId)
 * @method self setClientSecret(string $clientSecret)
 * @method self setUrlAuthorize(string $urlAuthorize)
 * @method self setUrlAccessToken(string $urlAccessToken)
 * @method self setUrlResourceOwnerDetails(string $urlResourceOwnerDetails)
 */
class <?= $this->clientClassName . PHP_EOL ?>
{
    const API_VERSION = "<?= $this->artifactVersion ?>";

    # List of available clients
<?php foreach ($this->classes as $class => $fqn): ?>
    const CLIENT_<?= strtoupper(preg_replace('/(?<=\\w)(?=[A-Z])/',"_$1", $class)) ?> = <?= $fqn ?>::class;
<?php endforeach; ?>

    /**
     * Stores the container builder required to create the APIs
     *
     * @var ContainerBuilder
     */
    private $container;

    /**
     * <?= $this->clientClassName ?> constructor.
     *
     * @param ContainerBuilder|null $container
     */
    public function __construct(ContainerBuilder $container = null)
    {
        $this->container = $container ?? new ContainerBuilder();

        // Set default config
        if (!$this->container->hasParameter("auth.client.options")) {
            $this->container->setParameter("auth.client.options", [
                'accountId' => getenv('ACCOUNT_ID'),
                'clientId' => getenv('CLIENT_ID'),
                'clientSecret' => getenv('CLIENT_SECRET'),
                'urlAuthorize' => getenv('URL_AUTHORIZE'),
                'urlAccessToken' => getenv('URL_ACCESS_TOKEN'),
                'urlResourceOwnerDetails' => ''
            ]);
        }

        if (!$this->container->hasParameter("api.baseUrl")) {
            $this->setApiUrl(getenv("API_URL"));
        }
    }

    /**
     * Just a helper object but all the config will be set in the container
     *
     * @return self
     */
    public function getConfig(): self
    {
        return $this;
    }

    /**
     * Sets the API Url configuration
     *
     * @param string $url
     * @return self
     */
    public function setApiUrl(string $url): self
    {
        $this->container->setParameter("api.baseUrl", $url);

        return $this;
    }

    /**
     * Used to set the config
     *
     * @param string $name
     * @param array $arguments
     * @return self
     */
    public function __call(string $name, array $arguments): self
    {
        // Get the options
        $options = $this->container->getParameter("auth.client.options");

        // Update the option only if it was set by default
        $optionName = lcfirst(ltrim($name, "set"));
        if (isset($options[$optionName])) {
            $options[$optionName] = trim(strval($arguments[0]));
        }

        // Update the options
        $this->container->setParameter("auth.client.options", $options);

        return $this;
    }

    /**
     * Creates/retrieves the requested client object
     *
     * @param string $class
     * @return <?= implode("|", array_merge(["AbstractApi"], array_keys($this->classes))) . PHP_EOL; ?>
     * @throws \Exception
     */
    public function getClient(string $class): \SalesForce\MarketingCloud\Api\AbstractApi
    {
        if (!$this->container->has($class)) {
            /** @var \GuzzleHttp\Client $httpClient */
            $httpClient = $this->container->get("http.client.adapter");

            // Auth container will not be preset in the container at first load
            if (!$this->container->has(AuthService::CONTAINER_ID)) {
                AuthServiceSetup::execute($this->container); // Sets the service AuthService::CONTAINER_ID
            }

            /** @var AuthService $authService */
            $authService = $this->container->get(AuthService::CONTAINER_ID);

            $this->container->set($class, new $class(
                $authService,
                $httpClient,
                (new Configuration())->setHost($this->container->getParameter("api.baseUrl"))
            ));
        }

        /** @var \SalesForce\MarketingCloud\Api\AbstractApi $client */
        $client = $this->container->get($class);

        return $client;
    }

<?php foreach ($this->classes as $class => $fqn): ?>
    /**
     * Creates a new <?= $class ?> object
     *
     * @return <?= $class . PHP_EOL ?>
     * @throws \Exception
     */
    public function get<?= $class ?>(): <?= $fqn . PHP_EOL; ?>
    {
        return $this->getClient(self::CLIENT_<?= strtoupper(preg_replace('/(?<=\\w)(?=[A-Z])/',"_$1", $class)) ?>);
    }

<?php endforeach; ?>
}
