<//php_template

namespace <?= $this->invokerPackage . "\\" . $this->apiPackage ?>;

use GuzzleHttp\Client as HttpClient;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use SalesForce\MarketingCloud\Configuration;
use SalesForce\MarketingCloud\Api\Client\ConfigBuilder;
use SalesForce\MarketingCloud\Authorization\AuthServiceBuilder;
use SalesForce\MarketingCloud\Event\Subscriber\AuthEventSub;

/**
 * Class <?= $this->clientClassName . PHP_EOL ?>
 *
 * NOTE: This class is auto generated
 *
 * @package <?= $this->invokerPackage . "\\" . $this->apiPackage . PHP_EOL ?>
 * @method self setAccountId(string $accountId)
 * @method self setClientId(string $clientId)
 * @method self setClientSecret(string $clientSecret)
 * @method self setUrlAuthorize(string $urlAuthorize)
 * @method self setUrlAccessToken(string $urlAccessToken)
 * @method self setUrlResourceOwnerDetails(string $urlResourceOwnerDetails)
 */
class <?= $this->clientClassName . PHP_EOL ?>
{
    const API_VERSION = "<?= $this->artifactVersion ?>";

    # List of available clients
<?php foreach ($this->classes as $class => $fqn): ?>
    const CLIENT_<?= strtoupper(preg_replace('/(?<=\\w)(?=[A-Z])/',"_$1", $class)) ?> = <?= $fqn ?>::class;
<?php endforeach; ?>

    /**
     * Stores the container builder required to create the APIs
     *
     * @var ContainerBuilder
     */
    private $container;

    /**
     * <?= $this->clientClassName ?> constructor.
     *
     * @param ConfigBuilder|null $configBuilder
     * @param HttpClient|null $httpClient
     */
    public function __construct(ConfigBuilder $configBuilder = null, HttpClient $httpClient = null)
    {
        $this->container = ($configBuilder ?? new ConfigBuilder())->getContainer();

        // Set the provided HTTP client
        $this->container->set("auth.http.client", $httpClient ?? new HttpClient());
    }

    /**
     * Creates/retrieves the requested client object
     *
     * @param string $class
     * @return <?= implode("|", array_merge(["AbstractApi"], array_keys($this->classes))) . PHP_EOL; ?>
     * @throws \Exception
     */
    public function getClient(string $class): \SalesForce\MarketingCloud\Api\AbstractApi
    {
        if (!$this->container->has($class)) {
            $configuration = new Configuration();

            // Creating the AUTH service
            $authService = AuthServiceBuilder::execute($this->container);

            // Event handling
            $eventDispatcher = $authService->getEventDispatcher();
            $eventDispatcher->addSubscriber(new AuthEventSub($configuration));

            // Registering the API client service
            $this->container->set($class, new $class(
                $authService,
                $this->container->get("auth.http.client"),
                $configuration
            ));
        }

        /** @var \SalesForce\MarketingCloud\Api\AbstractApi $client */
        $client = $this->container->get($class);

        return $client;
    }

<?php foreach ($this->classes as $class => $fqn): ?>
    /**
     * Creates a new <?= $class ?> object
     *
     * @return <?= $class . PHP_EOL ?>
     * @throws \Exception
     */
    public function get<?= $class ?>(): <?= $fqn . PHP_EOL; ?>
    {
        return $this->getClient(self::CLIENT_<?= strtoupper(preg_replace('/(?<=\\w)(?=[A-Z])/',"_$1", $class)) ?>);
    }

<?php endforeach; ?>
}
